[package]
name = "replay"
version = "0.1.0"
edition = "2021"

[dependencies]
codec = { path = "../codec" }
lob_core = { package = "lob-core", path = "../core" }
thiserror = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
