[package]
name = "orderbook"
version = "0.1.0"
edition = "2021"

[dependencies]
lob_core = { package = "core", path = "../core" }

[dev-dependencies]
criterion = { workspace = true }
rand = { workspace = true }
proptest = "1.4"

[[bench]]
name = "orderbook_bench"
harness = false
